// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p25
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:151

#ifndef _TAO_IDL_RTPSRPCC_ZPDZNE_H_
#define _TAO_IDL_RTPSRPCC_ZPDZNE_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include /**/ "rtps_export.h"
#include "tao/ORB.h"
#include "tao/Basic_Types_IDLv4.h"
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

namespace CORBA
{
  using namespace IDLv4;
}

TAO_END_VERSIONED_NAMESPACE_DECL

#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "tao/String_Manager_T.h"
#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Basic_Argument_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/BD_String_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"
#include /**/ "dds/Versioned_Namespace.h"

#include "RtpsCoreC.h"
#include "dds/DdsDcpsGuidC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO OpenDDS_Rtps_Export

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



OPENDDS_END_VERSIONED_NAMESPACE_DECL



OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:37

namespace DDS
{
  // TAO_IDL - Generated from
  // be/be_type.cpp:260

  

  struct SampleIdentity;

  typedef
    ::TAO_Fixed_Var_T<
        SampleIdentity
      >
    SampleIdentity_var;

  typedef
    SampleIdentity &
    SampleIdentity_out;

  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:50

  

  struct OpenDDS_Rtps_Export SampleIdentity
  {
    // TAO_IDL - Generated from
    // be/be_type.cpp:304

    
    typedef SampleIdentity_var _var_type;
    typedef SampleIdentity_out _out_type;
    
    OpenDDS::DCPS::GUID_t writer_guid;
    OpenDDS::RTPS::SequenceNumber_t sequence_number;
  };
  // TAO_IDL - Generated from
  // be/be_visitor_module/module_ch.cpp:37

  namespace RPC
  {
    // TAO_IDL - Generated from
    // be/be_visitor_typedef/typedef_ch.cpp:402

    typedef char * InstanceName;
    typedef ::CORBA::String_var InstanceName_var;
    typedef ::CORBA::String_out InstanceName_out;
    // TAO_IDL - Generated from
    // be/be_visitor_enum/enum_ch.cpp:46

    enum RemoteExceptionCode_t
    {
      REMOTE_EX_OK,
      REMOTE_EX_UNSUPPORTED,
      REMOTE_EX_INVALID_ARGUMENT,
      REMOTE_EX_OUT_OF_RESOURCES,
      REMOTE_EX_UNKNOWN_OPERATION,
      REMOTE_EX_UNKNOWN_EXCEPTION
    };

    typedef RemoteExceptionCode_t &RemoteExceptionCode_t_out;
    // TAO_IDL - Generated from
    // be/be_type.cpp:260

    

    struct RequestHeader;

    typedef
      ::TAO_Var_Var_T<
          RequestHeader
        >
      RequestHeader_var;

    typedef
      ::TAO_Out_T<
          RequestHeader
        >
      RequestHeader_out;

    
    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:50

    

    struct OpenDDS_Rtps_Export RequestHeader
    {
      // TAO_IDL - Generated from
      // be/be_type.cpp:304

      
      typedef RequestHeader_var _var_type;
      typedef RequestHeader_out _out_type;
      
      DDS::SampleIdentity requestId;
      ::TAO::String_Manager instanceName;
    };
    // TAO_IDL - Generated from
    // be/be_type.cpp:260

    

    struct ReplyHeader;

    typedef
      ::TAO_Fixed_Var_T<
          ReplyHeader
        >
      ReplyHeader_var;

    typedef
      ReplyHeader &
      ReplyHeader_out;

    
    // TAO_IDL - Generated from
    // be/be_visitor_structure/structure_ch.cpp:50

    

    struct OpenDDS_Rtps_Export ReplyHeader
    {
      // TAO_IDL - Generated from
      // be/be_type.cpp:304

      
      typedef ReplyHeader_var _var_type;
      typedef ReplyHeader_out _out_type;
      
      DDS::SampleIdentity relatedRequestId;
      DDS::RPC::RemoteExceptionCode_t remoteEx;
    };
  
  
  // TAO_IDL - Generated from
  // be/be_visitor_module/module_ch.cpp:65

  
  } // module DDS::RPC


// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:65


} // module DDS
// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:66




OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:934

  

  template<>
  class Arg_Traits< ::DDS::SampleIdentity>
    : public
        Fixed_Size_Arg_Traits_T<
            ::DDS::SampleIdentity,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };

#if !defined (_INSTANCENAME255__ARG_TRAITS_)
#define _INSTANCENAME255__ARG_TRAITS_

  struct InstanceName_255 {};

  template<>
  class Arg_Traits<InstanceName_255>
    : public
        BD_String_Arg_Traits_T<
            CORBA::String_var,
            255,
            TAO::Any_Insert_Policy_Noop
        >
  {
  };

#endif /* end #if !defined */
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:892

  

  template<>
  class Arg_Traits< ::DDS::RPC::RemoteExceptionCode_t>
    : public
        Basic_Arg_Traits_T<
            ::DDS::RPC::RemoteExceptionCode_t,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:934

  

  template<>
  class Arg_Traits< ::DDS::RPC::RequestHeader>
    : public
        Var_Size_Arg_Traits_T<
            ::DDS::RPC::RequestHeader,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:934

  

  template<>
  class Arg_Traits< ::DDS::RPC::ReplyHeader>
    : public
        Fixed_Size_Arg_Traits_T<
            ::DDS::RPC::ReplyHeader,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:60




OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:45



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::SampleIdentity &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::SampleIdentity &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_enum/cdr_op_ch.cpp:36



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &strm, DDS::RPC::RemoteExceptionCode_t _tao_enumerator);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &strm, DDS::RPC::RemoteExceptionCode_t &_tao_enumerator);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:45



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::RPC::RequestHeader &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::RPC::RequestHeader &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:45



OPENDDS_END_VERSIONED_NAMESPACE_DECL


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

OpenDDS_Rtps_Export ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDS::RPC::ReplyHeader &);
OpenDDS_Rtps_Export ::CORBA::Boolean operator>> (TAO_InputCDR &, DDS::RPC::ReplyHeader &);

TAO_END_VERSIONED_NAMESPACE_DECL


OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1666



OPENDDS_END_VERSIONED_NAMESPACE_DECL

#if defined (__ACE_INLINE__)
#include "RtpsRpcC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

